ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-no_b_mass'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'UV_GQQt = ', UV_GQQT
      WRITE(*,2) 'UVWfct_G_2 = ', UVWFCT_G_2
      WRITE(*,2) 'R2_DDA = ', R2_DDA
      WRITE(*,2) 'R2_UUA = ', R2_UUA
      WRITE(*,2) 'R2_DDZ_V2 = ', R2_DDZ_V2
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_UUZ_V5 = ', R2_UUZ_V5
      WRITE(*,2) 'R2_GGHt = ', R2_GGHT
      WRITE(*,2) 'R2_GGZup = ', R2_GGZUP
      WRITE(*,2) 'R2_GGZdown = ', R2_GGZDOWN
      WRITE(*,2) 'R2_GGZAup = ', R2_GGZAUP
      WRITE(*,2) 'R2_GGZAdown = ', R2_GGZADOWN
      WRITE(*,2) 'R2_GGAAdown = ', R2_GGAADOWN
      WRITE(*,2) 'R2_GGAAup = ', R2_GGAAUP
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'R2_GQQ = ', R2_GQQ
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'UV_GQQg_1eps = ', UV_GQQG_1EPS
      WRITE(*,2) 'UV_GQQq_1eps = ', UV_GQQQ_1EPS
      WRITE(*,2) 'UVWfct_G_2_1eps = ', UVWFCT_G_2_1EPS
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_1003 = ', GC_1003
